# Top-level configuration
name = "ai-flashcards"
main = "dist/_worker.js"
compatibility_date = "2025-03-12"
workers_dev = true
pages_build_output_dir = "./dist"

# Site configuration
[site]
bucket = "dist"

# Build configuration
[build]
command = "pnpm run build"

# KV namespaces
[[kv_namespaces]]
binding = "SESSION_STORE"
id = "${KV_SESSION_ID}"

# Production environment
[env.production]
routes = [
  { pattern = "ai-flashcards.pages.dev/*", zone_id = "${CLOUDFLARE_ACCOUNT_ID}" }
]

[env.production.vars]
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_KEY = "${SUPABASE_KEY}"

# Preview environment
[env.preview.vars]
SUPABASE_URL = "${SUPABASE_URL}"
SUPABASE_KEY = "${SUPABASE_KEY}" 