# Wrangler configuration for AI Flashcards
name = "ai-flashcards"
main = "./.astro/cloudflare/_worker.js"
compatibility_date = "2024-07-01"

# Environment variables
[vars]
ENVIRONMENT = "production"

[site]
bucket = "./dist"

[build]
command = "pnpm run build"

# Additional developer tools
[dev]
port = 8788
local_protocol = "http" 