# Wrangler configuration for AI Flashcards
name = "ai-flashcards"
main = "./.astro/cloudflare/_worker.js"
compatibility_date = "2024-07-01"

# Deployment settings
workers_dev = true
# routes = [
#   { pattern = "ai-flashcards.yourdomain.com", custom_domain = true }
# ]

# Environment variables
[vars]
ENVIRONMENT = "production"

# Assets configuration
[assets]
bucket = "./dist"

# Pages configuration
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SESSION"
id = "KV_SESSION_ID"

[build]
command = "pnpm run build"

# Additional developer tools
[dev]
port = 8788
local_protocol = "http" 